import blogImages from "../assets/images/blog_pics/blogImages";

export const blogs = [
  {
    blogId: 1,
    userName: "User 1",
    time: "oct 11",
    title: "Title 1",
    contentType: "image",
    textDescription:
      "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repudiandae adipis amet consectetur adipisicing elit. Repudiandae adipis lorem voluptas facere nobis provident ",
    textContent:
      "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repudiandae adipisci dolorem voluptas facere nobis provident est ipsa deserunt dignissimos minus. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Suscipit earum impedit eius exercitationem a magni animi provident fuga cumque explicabo praesentium quisquam consequatur ipsam placeat, deleniti facilis ab ...",
    profilePicLink: null,
    imgContent: blogImages.blogPic_1,
    tags: ["tech", "computer", "science", "pc"],
    likeCount: 45,
    disLikeCount: 4,
    isSaved: false,
    isFollowed: true,
    isLiked: true,
    isDisLiked: false,
  },
  {
    blogId: 2,
    userName: "User 2",
    time: "oct 10",
    title: "Title 2",
    contentType: "image",
    textDescription:
      "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repudiandae adipis",
    textContent:
      "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repudiandae adipisci dolorem voluptas facere nobis provident est ipsa deserunt dignissimos minus. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Suscipit earum impedit eius exercitationem a magni animi provident fuga cumque explicabo praesentium quisquam consequatur ipsam placeat, deleniti facilis ab ...",
    profilePicLink: null,
    imgContent: blogImages.blogPic_1,
    tags: ["tech", "computer", "science", "pc"],
    likeCount: 32,
    disLikeCount: 2,
    isSaved: true,
    isFollowed: false,
    isLiked: true,
    isDisLiked: false,
  },
  {
    blogId: 3,
    userName: "User 3",
    time: "oct 9",
    title: "Title 3",
    contentType: "image",
    textDescription:
      "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repudiandae adipis",
    textContent:
      "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repudiandae adipisci dolorem voluptas facere nobis provident est ipsa deserunt dignissimos minus. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Suscipit earum impedit eius exercitationem a magni animi provident fuga cumque explicabo praesentium quisquam consequatur ipsam placeat, deleniti facilis ab ...",
    profilePicLink: null,
    imgContent: null,
    tags: ["tech", "computer", "science", "pc"],
    likeCount: 26,
    disLikeCount: 1,
    isSaved: true,
    isFollowed: true,
    isLiked: false,
    isDisLiked: true,
  },
  {
    blogId: 4,
    userName: "User 4",
    time: "oct 8",
    title: "Title 4",
    contentType: "image",
    textDescription:
      "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repudiandae adipis",
    textContent:
      "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repudiandae adipisci dolorem voluptas facere nobis provident est ipsa deserunt dignissimos minus. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Suscipit earum impedit eius exercitationem a magni animi provident fuga cumque explicabo praesentium quisquam consequatur ipsam placeat, deleniti facilis ab ...",
    profilePicLink: null,
    imgContent: blogImages.blogPic_1,
    tags: ["tech", "computer", "science", "pc"],
    likeCount: 22,
    disLikeCount: 0,
    isSaved: false,
    isFollowed: true,
    isLiked: false,
    isDisLiked: true,
  },
  {
    blogId: 5,
    userName: "User 5",
    time: "oct 7",
    title: "Title 5",
    contentType: "image",
    textDescription:
      "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repudiandae adipis amet consectetur adipisicing elit. Repudiandae adipis lorem voluptas facere nobis provident ",
    textContent:
      "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repudiandae adipisci dolorem voluptas facere nobis provident est ipsa deserunt dignissimos minus. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Suscipit earum impedit eius exercitationem a magni animi provident fuga cumque explicabo praesentium quisquam consequatur ipsam placeat, deleniti facilis ab ...",
    profilePicLink: null,
    imgContent: blogImages.blogPic_1,
    tags: ["tech", "computer", "science", "pc"],
    likeCount: 54,
    disLikeCount: 4,
    isSaved: true,
    isFollowed: false,
    isLiked: true,
    isDisLiked: false,
  },
];
